# Oppgaver i MAT102, uke 8

## Oppgave 1

1. Gjør oppgave 10.1.1 i MIP. Bruk gjerne python til det.
2. Gjør oppgave 10.1.2 i MIP. Bruk gjerne python til det hvis du vil.
3. Gjør oppgave 10.1.5 i MIP.

## Oppgave 2

Undersøk om følgende vektorer står vinkelrett på hverandre

1. $[3,1]$ og $[2, -6]$
2. $[1,2,3]$ og $[-3,2,-1]$
3. $[-1,-1,5]$ og $[3,-7,-1]$
4. $[\cos(t), \sin(t)]$ og $[\sin(t), -\cos(t)]$ for ukjent $t \in \mathbb{R}$

ortogonale dersom prikkproduketet = 0, gjelder 1 og 4, resten er ikke ortogonale.


## Oppgave 3

Løs følgende oppgaver fra MIP for hånd eller ved hjelp av python:

1. 10.4.1, 10.4.2 og 10.4.5
2. 10.4.6
3. 10.5.1
4. 10.5.5

## Hint til oppgavene

Vinkelen $\theta$ mellom to vektorer $\vec a$ og $\vec b$ oppfylder $\vec a \cdot \vec b = \cos(\theta) \cdot |\vec a| \cdot |\vec b|$

En matrise kan skrives inn i python på denne måten

In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [1,2,3,4,5,6],
    [7,8,9,1,2,3]
])

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 1],
    [2, 3]
])

Vi kan vise matrisen ved å skrive navnet på den:

In [ ]:
A

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

Produktet av matriser betegnes `@` i python:

In [ ]:
C = A @ B
C

array([[107,  83],
       [107, 119]])

Koden under reduserer matriser.

In [ ]:
def normer_forste_element(a):
    # Finn indeksen til det første elementet i vektoren a som ikke er null
    forste_ikke_null_element_indeks = np.argmax(a != 0)

    # Hent verdien til det første ikke-null elementet
    forste_ikke_null_element = a[forste_ikke_null_element_indeks]

    # Returner den normaliserte vektoren, der alle elementer er delt på det første ikke-null elementet
    return a / forste_ikke_null_element

def gauss_jordan(A):
    # Hvis matrisen kun består av nuller, returner den uendret
    if np.all(A == 0):
        return A

    # Hvis matrisen har én rad, normaliser den første radens første ikke-null element
    elif len(A) == 1:
        A[0] = normer_forste_element(A[0])
        return A
    else:
        # Beregn radenes summer for å normalisere matrisen
        # (Dette er ikke nødvendig, men gjør tallene finere å regne med)
        rad_summer = np.sum(A, axis=1)
        A = A / rad_summer[:, None]  # Normaliser hver rad ved å dele med radens sum

        # Finn kolonner som inneholder ikke-null elementer
        ikke_null_kolonner = np.any(A != 0, axis=0)

        # Finn indeksen til den første kolonnen med ikke-null elementer
        forste_ikke_null_kolonne_indeks = np.argmax(ikke_null_kolonner)

        # Finn indeksen til raden med største verdi i den valgte kolonnen (pivot rad)
        pivot_rad_indeks = np.argmax(A[:, forste_ikke_null_kolonne_indeks])

        # Normaliser pivot raden
        pivot_rad = normer_forste_element(A[pivot_rad_indeks])

        # Bytt plass på pivot raden og den første raden
        A[pivot_rad_indeks] = A[0]
        A[0] = pivot_rad

        # Utfør eliminering for å gjøre alle elementene under pivoten null
        A[1:] = A[1:] - (A[1:, 0] / A[0, 0])[:, None] * A[0][None, :]

        # Kall gauss_jordan rekursivt på den nedre delmatrisen
        A[1:, 1:] = gauss_jordan(A[1:, 1:])

        # Gjør den første raden null over pivot-posisjonene til de øvrige radene.
        for rad in A[1:]:
            if np.any(rad != 0):  # Hvis raden ikke er null
                # Finn indeksen til det første ikke-null elementet i raden
                forste_ikke_null_element_indeks = np.argmax(rad != 0)

                # Trekk et tall gange den akutelle raden fra den første raden slik at første raden blir null over
                # pivot-elementet til den aktuelle raden
                A[0] = A[0] - (A[0, forste_ikke_null_element_indeks] / rad[forste_ikke_null_element_indeks]) * rad

    # Returner den resulterende matrisen
    return A


Her er et eksempel på bruk:

In [ ]:
gauss_jordan(A)

array([[ 1. ,  0. , -1. , -5. , -6. , -7. ],
       [ 0. ,  1. ,  2. ,  4.5,  5.5,  6.5]])

In [ ]:
gauss_jordan(B)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

La oss løse eksempel 2 på side 317 i MIP ved hjelp av koden over:

In [ ]:
M = np.array([
    [2, 9, 0, 32, 13],
    [-1, 1, 6, 28, -19],
    [1, 2, -3, -7, 13]
])

In [ ]:
gauss_jordan(M)

array([[ 1.,  0.,  0., 34.,  2.],
       [ 0.,  1.,  0., -4.,  1.],
       [ 0.,  0.,  1., 11., -3.]])

Vi ser at siste kolonne er for høyresiden av ligningen og at det er fire kolonner for ukjente variabler. Siden det er tre pivotkolonner er det tre bundne parametre og en fri parameter svarende til den nest siste kolonne som ikke er en pivotkolonne.